version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DB_HOST=dpg-d3jmkoq4d50c73fb03og-a
      - DB_USER=inventory_user
      - DB_PASS=ynmFwXQUUSOo7kMhHYJXaA2juWcIJxAo
      - DB_NAME=inv_system_ps8n
      - DB_PORT=5432
    volumes:
      - ./uploads:/var/www/html/uploads
    networks:
      - inventory-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: inv_system
      MYSQL_USER: inventory_user
      MYSQL_PASSWORD: inventory_password
    volumes:
      - db_data:/var/lib/mysql
      - ./inv_system (2).sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - inventory-network

volumes:
  db_data:

networks:
  inventory-network:
    driver: bridge